<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-CD2E1TO" name="com.helinfengxs.cases.LoginCases" tests="1" failures="0" timestamp="2 Jun 2021 06:30:17 GMT" time="3.717" errors="1">
  <testcase name="loginCorrect" time="3.717" classname="com.helinfengxs.cases.LoginCases">
    <error type="java.lang.AssertionError" message="The following asserts failed:
expected [成功] but found [null]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [成功] but found [null]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:38)
	at com.helinfengxs.util.Util.testNgAssert(Util.java:388)
	at com.helinfengxs.cases.LoginCases.loginCorrect(LoginCases.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at com.helinfengxs.api.TestNgIsOk.main(TestNgIsOk.java:19)
]]>
    </error>
  </testcase> <!-- loginCorrect -->
</testsuite> <!-- com.helinfengxs.cases.LoginCases01 -->
